name: Python application test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install streamlit
        pip install tqdm
        pip install langchain
        pip install plotly
        pip install plotly-express
        
    - name: Run tests
      run: |
        python -m unittest discover -s . -p 'test_*.py'
